# TODO: 適切な名前にする
name: Ci

on:
  push:
    # HACK: 正規表現
    branches: [ main, 'feat/**', 'fix/**', 'update/**']
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn fixpack
    - run: yarn lint
    - run: yarn type-check
