name: Release
on:
  push:
    branches:
      - release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
